name: CI

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-13]
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: xCode
        run: sudo xcode-select -s /Applications/Xcode_14.3.app/Contents/Developer/

      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x

      - name: Install Workloads
        run: dotnet workload install android ios wasm-tools

      - name: Build Release
        run: dotnet build -c Release
